ICON_URLS = [
  ["bill, expenses, invoice, receipt, internet bill ", "https://cdn0.iconfinder.com/data/icons/work-from-home-18/512/InternetBill-bill-invoice-receipt-expenses-128.png"],
  ["bill, expenses, invoice, receipt, internet bill ", "https://cdn0.iconfinder.com/data/icons/work-from-home-19/512/InternetBill-bill-invoice-receipt-expenses-128.png"],
  ["bill, expenses, invoice, receipt, internet bill, payment ", "https://cdn0.iconfinder.com/data/icons/work-from-home-17/512/InternetBill-bill-invoice-receipt-expenses-128.png"],
  ["expenses ", "https://cdn3.iconfinder.com/data/icons/iconpark-vol-8/48/expenses-128.png"],
  ["expenses, one ", "https://cdn3.iconfinder.com/data/icons/iconpark-vol-8/48/expenses-one-128.png"],
  ["maintenance, repair, service ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__utilities_service_repair_maintenance-128.png"],
  ["fork, food, kitchen ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__restaurant_food_expense_fork-128.png"],
  ["bag, money, revenew ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__bonus_money_bag_revenew-128.png"],
  ["gear, maintenance, service ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__service_gear_technical_maintenance-128.png"],
  ["airplane, flight, travel ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__airplane_flight_travel_transport-128.png"],
  ["bill, fee, tax ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__tax_fee_expenses_bill-128.png"],
  ["label, tag, price ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__label_tag_shopping_price-128.png"],
  ["car, fuel, gas, station ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__gas_fuel_station_car-128.png"],
  ["insurance, protection, safety, shield ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__insurance_shield_protection_safety-128.png"],
  ["money, cash, finance ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__money_transaction_transfer_send-128.png"],
  ["ambulance, healthcare, medicine ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__healthcare_medicine_expense_ambulance-128.png"],
  ["home, house, building ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__house_home_flat_facilities-128.png"],
  ["computer, device, electronics ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__electronics_computer_device_technology-128.png"],
  ["activities, dumbbell, gym, sport ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__gym_sport_activities_dumbbell-128.png"],
  ["earnings, income, passive ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__passive_income_earnings_money-128.png"],
  ["baby, care, kid, stroller ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__kid_stroller_baby_child_care-128.png"],
  ["drugs, medicine, pills ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__pills_medicine_drugs_health-128.png"],
  ["clothes, fashion, tshirt ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__clothes_tshirt_fashion_outfit-128.png"],
  ["gift, present, box ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__gift_present_box_birthday-128.png"],
  ["metro, tickets, train, transport ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__transport_tickets_train_metro-128.png"],
  ["hobby, kite, leasure ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__hobby_leasure_kite_vacation-128.png"],
  ["suitcase, travel, vacation ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__travel_case_vacation_suitcase-128.png"],
  ["bag, shopping, store ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__shopping_shop_store_bag-128.png"],
  ["drama, entertainment, theater ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__entertainment_theater_drama_mask-128.png"],
  ["deposit, safe, savings ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__savings_safe_deposit_percentage-128.png"],
  ["earnings, income, wallet ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__salary_wallet_income_earnings-128.png"],
  ["car, drive, service ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__car_service_drive_expenses-128.png"],
  ["atm, cashout, money ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__withdraw_atm_cashout_money-128.png"],
  ["miscellaneous, multiple, other ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__miscellaneous_multiple_other_purpose-128.png"],
  ["beauty, health, heart ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__beauty_health_cosmetics_heart-128.png"],
  ["apple, food, grocery ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__food_apple_grocery_gastronomy-128.png"],
  ["bistro, cafe, coffee ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__cafe_coffee_beverages_bistro-128.png"],
  ["calendar, care, donation, heart ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__donation_social_care_calendar_heart-128.png"],
  ["clock, pending, time ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__pending_transaction_clock_wait-128.png"],
  ["email, newsletter, subscription ", "https://cdn0.iconfinder.com/data/icons/expenses-vs-income/30/__subscription_email_fees_newsletter-128.png"]
  ]
